"""file update

Revision ID: 0161700250e4
Revises: ff36be93147d
Create Date: 2023-06-24 18:22:17.798134

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '0161700250e4'
down_revision = 'ff36be93147d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('page_num', sa.Integer(), nullable=True),
    sa.Column('golden_name', sa.String(), nullable=True),
    sa.Column('targets', sa.String(), nullable=True),
    sa.Column('candidate', sa.String(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remarks')
    # ### end Alembic commands ###
