"""bundle update

Revision ID: 737e1ed76fd8
Revises: 0161700250e4
Create Date: 2023-06-24 22:06:45.972579

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '737e1ed76fd8'
down_revision = '0161700250e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundles', sa.Column('message', sa.String(), nullable=True))
    op.add_column('bundles', sa.Column('execTime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bundles', 'execTime')
    op.drop_column('bundles', 'message')
    # ### end Alembic commands ###
