"""status

Revision ID: b48a1cb7c15f
Revises: ddd7dddfad69
Create Date: 2023-06-24 16:53:16.108997

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'b48a1cb7c15f'
down_revision = 'ddd7dddfad69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundles', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bundles', 'status')
    # ### end Alembic commands ###
