"""bundle update

Revision ID: d271b55daf12
Revises: 737e1ed76fd8
Create Date: 2023-06-24 22:08:47.116482

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'd271b55daf12'
down_revision = '737e1ed76fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bundles', 'execTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundles', sa.Column('execTime', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
