"""similarity

Revision ID: d3c691a384d6
Revises: d271b55daf12
Create Date: 2023-06-25 01:47:02.112292

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'd3c691a384d6'
down_revision = 'd271b55daf12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remarks', sa.Column('similarity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remarks', 'similarity')
    # ### end Alembic commands ###
