"""feedback

Revision ID: f695b7657e72
Revises: d3c691a384d6
Create Date: 2023-06-25 03:22:57.080969

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'f695b7657e72'
down_revision = 'd3c691a384d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remarks', sa.Column('is_correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remarks', 'is_correct')
    # ### end Alembic commands ###
